/*
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Copyright (c) 2013 VigLink. Rights reserved and patent(s) pending.
*/
(function(i){var e,q=function(a,b){try{return("function"===typeof window[b]||"object"===typeof window[b])&&a instanceof window[b]}catch(d){}return!1},c={_breaker:{},each:function(a,b){var d,f;if("object"===c.type(a)&&a.hasOwnProperty)for(d in a){if(a.hasOwnProperty(d)&&b(a[d],d)===c._breaker)break}else if(a){d=0;for(f=a.length;d<f&&b(a[d],d)!==c._breaker;d++);}},extend:function(a){var b,d,f,c,g=arguments.length;a=a||{};for(d=1;d<g;d++)if(c=arguments[d],void 0!==c&&null!==c)for(f in c)b=c[f],a!==b&&
void 0!==b&&(a[f]=b);return a},noop:function(){},type:function(a){return null===a?"null":void 0===a?"undefined":q(a,"HTMLElement")||"object"===typeof a&&1===a.nodeType&&"string"===typeof a.nodeName?"element":q(a,"HTMLDocument")||"object"===typeof a&&("defaultView"in a||"parentWindow"in a)?"document":a==a.window?"window":Object.prototype.toString.call(a).slice(8,-1).toLowerCase()}};c.extend(c,{addClass:function(a,b){c.hasClass(a,b)||(a.className=(a.className?a.className+" ":"")+b)},attrValues:function(a,
b,d){return(b=a[b])?b.split(d||" "):[]},bind:function(a,b){return function(){return a.apply(b,arguments)}},cache:function(){var a={},b="vglnk_"+(new Date).getTime(),d=0;return function(f,c,g){if(f){var h=f[b];if(h||void 0!==g)return h||(h=++d),a[h]||(f[b]=h,a[h]={}),void 0!==g&&(a[h][c]=g),"string"===typeof c?a[h][c]:a[h]}}}(),canonicalizeHostname:function(a){"string"===typeof a&&(a=c.createA(a));return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""},clone:function(a){return c.extend({},
a)},contains:function(a,b){return-1!==c.indexOf(a,b)},context:function(a){"element"===c.type(a)&&(a=a.ownerDocument);"document"===c.type(a)&&(a=a.defaultView||a.parentWindow);if("window"===c.type(a))return a},containsPII:function(a){return/\b[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}\b/i.test(a)},contextIsAncestor:function(a,b){for(var d=a.self;d.parent&&d.parent!==d;)if(d=d.parent,d===b)return!0;return!1},cors:function(a){var b,d=function(){eval(b.responseText)};b=new window.XMLHttpRequest;
b.onreadystatechange=function(){4===b.readyState&&200===b.status&&d()};try{b.open("GET",a),b.withCredentials=!0,b.send()}catch(f){return!1}},createA:function(a,b){return c.createEl("a",{href:a,target:b})},createEl:function(a,b,d,f){var t;a=(f||document).createElement(a);b=b||{};d=d||{};for(t in b)void 0!==b[t]&&(a[t]=b[t]);c.css(a,d);return a},css:function(a,b){for(var d in b)try{a.style[d]=b[d]}catch(f){}return a},destructing:function(a){var b=!1,d;return function(){b||(d=a.apply(null,arguments),
b=!0);return d}},escapeRegExp:function(){var a;return function(b){a=a||RegExp("([.*+?^${}()|[\\]\\\\])","g");return b.replace(a,"\\$1")}}(),eventLink:function(a){var b,d=a.target||a.srcElement;do{try{b=d.nodeType}catch(f){break}if(1===b&&(a=d.tagName.toUpperCase(),"A"===a||"AREA"===a))return d;d=d.parentNode}while(d)},exceptionLogger:function(){var a=!1,b=c.noop;return function(d,f){if(void 0!==f)a=f,b=d;else return function(){if(a)try{return d.apply(this,arguments)}catch(f){b(f)}else return d.apply(this,
arguments)}}}(),find:function(a,b){var d;c.each(a,function(a,t){if(b(a,t))return d=a,c._breaker});return d},generateNodeFilter:function(){var a=function(a,f){var c,g;f=","+f.join(",")+",";c=0;for(g=a.length;c<g;c++)if(b(a[c],f))return!0;return!1},b=function(a,b){return-1!==b.indexOf(","+a+",")};return function(d){d=c.extend({custom:null,classes:[],rels:[],tags:[]},d);d.tags.length&&(d.tags=","+d.tags.join(",").toLowerCase()+",");return function(f,t){t=c.extend({ancestors:!0,self:!0},t);var g=!0,h=
!0,va=function(f,t){var h;if(h=!(d.tags.length&&b(f.nodeName.toLowerCase(),d.tags))){if(h=d.classes.length){h=d.classes;var g=c.attrValues(f,"className");h=a(h,g)}if(h=!h){if(h=d.rels.length)h=d.rels,g=c.attrValues(f,"rel"),h=b(f.nodeName.toLowerCase(),",a,")&&a(h,g);h=!h&&!("function"===c.type(d.custom)&&d.custom(f,t))}}return h},h=!t.self||va(f,!0);if(t.ancestors)for(;f.parentNode;)if(f=f.parentNode,1===f.nodeType&&!va(f,!1)){g=!1;break}return h&&g}}}(),fromQuery:function(a){"?"===a.substr(0,1)&&
(a=a.substr(1));a=a.split("\x26");var b={};c.each(a,function(a){a=a.split("\x3d");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return b},geometry:function(){var a,b=arguments.length,d=Infinity,f=Infinity,t=-Infinity,g=-Infinity,h;for(a=0;a<b;a++)h=c.position(arguments[a]),d=Math.min(d,h.x),f=Math.min(f,h.y),t=Math.max(t,h.x+arguments[a].offsetWidth),g=Math.max(g,h.y+arguments[a].offsetHeight);return{x:d,y:f,w:t-d,h:g-f,x1:d,y1:f,x2:t,y2:g}},getActualHref:function(a){return c.cache(a,"href")||
a.href},hasAttrValue:function(a,b,d,f){return b?c.contains(c.attrValues(a,b,f),d):!1},hasClass:function(a,b){return c.hasAttrValue(a,"className",b)},hasRel:function(a,b){return c.hasAttrValue(a,"rel",b)},indexOf:Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b)}:function(a,b){var d,f;d=0;for(f=a.length;d<f;d++)if(a[d]===b)return d;return-1},isArray:function(a){return"array"===c.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&a.isDefaultPrevented()||
!1===a.returnValue||!0===a.defaultPrevented},jsonp:function(a){var b=document.getElementsByTagName("script")[0];a=c.createEl("script",{type:"text/javascript",src:a});b.parentNode.insertBefore(a,b)},map:function(a,b){var d=[];c.each(a,function(a,c){void 0!==a&&(d[c]=b(a))});return d},matches:function(){try{return this.Sizzle.matchesSelector.apply(this.Sizzle,arguments)}catch(a){return!0}},on:function(){var a;return function(b,d,f){var t,g;if(1===arguments.length)a=b;else{if(2===arguments.length){if(!a)return;
f=d;d=b;b=a}try{t=b["on"+d]}catch(h){}"function"===typeof t&&(b["on"+d]=c.bind(function(a){a=a||window.event;var d=t.apply(b,arguments);this.exceptionLogger(function(){return a?(void 0!==d&&!1!==a.returnValue&&(a.returnValue=d),c.isDefaultPrevented(a)&&"function"===c.type(a.preventDefault)&&a.preventDefault(),a.returnValue):d})()},this));g=c.exceptionLogger(function(){if(a.enabled())return f.apply(null,arguments)});b.addEventListener?b.addEventListener(d,g,!1):b.attachEvent&&b.attachEvent("on"+d,
g)}}}(),position:function(a){var b,d=0,f=0,c=0,g=0;if(!a.offsetParent)return!1;b=a;do d+=b.offsetLeft,f+=b.offsetTop,b=b.offsetParent;while(b);b=a;do c+=b.scrollLeft,g+=b.scrollTop,b=b.parentNode;while(b&&b!==document.body);return{x:d-c,y:f-g}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},ready:function(){var a=!1,b=[],d=!1,f,t,g,h,e;document.addEventListener?g=function(){document.removeEventListener("DOMContentLoaded",g,!1);e()}:document.attachEvent&&(h=
function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",h),e())});f=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return e();if(document.addEventListener)document.addEventListener("DOMContentLoaded",g,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",h);var b=!1;try{b=null===window.frameElement}catch(d){}document.documentElement.doScroll&&b&&t()}c.on(window,"load",e)}};t=function(){if(!d){try{document.documentElement.doScroll("left")}catch(a){setTimeout(c.exceptionLogger(t),
1);return}e()}};e=function(){if(!d){if(!document.body)return setTimeout(c.exceptionLogger(e),13);d=!0;b&&(c.each(b,function(a){a()}),b=null)}};return function(a){f();d?a():b.push(a)}}(),reformatKeys:function(a){var b,d,f=function(a){return"_"+a.toLowerCase()};for(b in a)d=b.replace(/([A-Z])/g,f),"object"===c.type(a[b])&&(a[b]=c.reformatKeys(a[b])),d!==b&&(a[d]=a[b],delete a[b]);return a},removeClass:function(a,b){if(c.hasClass(a,b)){var d,f,t=c.attrValues(a,"className");d=0;for(f=t.length;d<f;d++)t[d]===
b&&delete t[d];a.className=t.join(" ")}},request:function(a,b,d){var f,t;d=c.extend({fn:c.noop,"return":!1,timeout:null},d);"string"===typeof d.fn?b=c.extend(b,{jsonp:d.fn}):"function"===typeof d.fn&&(f=c.destructing(d.fn),t=c.uniqid("vglnk_jsonp_"),b=c.extend(b,{jsonp:t}),window[t]=c.exceptionLogger(function(){f.apply(this,arguments);window[t]=void 0}),null!==d.timeout&&setTimeout(c.exceptionLogger(f),d.timeout));b=c.extend({format:"jsonp"},b);b=c.toQuery(b);a=a+(b.length?"?":"")+b;return d["return"]?
a:c.traits.cors&&!1!==c.cors(a)?!0:c.jsonp(a)},select:function(){try{return this.Sizzle.apply(this.Sizzle,arguments)}catch(a){return[]}},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,0)}catch(b){var d,f,c=[];d=0;for(f=a.length;d<f;d++)c[d]=a[d];return c}},toQuery:function(a){var b,d="";for(b in a)null!==a[b]&&void 0!==a[b]&&(d+="\x26"+encodeURIComponent(b)+"\x3d"+encodeURIComponent(a[b]));return d.substr(1)},transmitsPII:function(a){return c.containsPII(a+" "+
document.referrer)},updateUrl:function(a,b){return c.extend(c.createA(a),b).href},uniqid:function(){var a=0;return function(b){return(b||"")+(new Date).getTime()+a++}}()});var r=function(){var a=c.find(c.toArray(arguments),function(a){return"function"===c.type(a)});a&&(c.Sizzle=a())};r.amd=!0;var u=window,p=function(a,b,d,f){var c,g,h,e,G;(b?b.ownerDocument||b:w)!==B&&N(b);b=b||B;d=d||[];if(!a||"string"!==typeof a)return d;if(1!==(e=b.nodeType)&&9!==e)return[];if(H&&!f){if(c=Ma.exec(a))if(h=c[1])if(9===
e)if((g=b.getElementById(h))&&g.parentNode){if(g.id===h)return d.push(g),d}else return d;else{if(b.ownerDocument&&(g=b.ownerDocument.getElementById(h))&&ba(b,g)&&g.id===h)return d.push(g),d}else{if(c[2])return O.apply(d,b.getElementsByTagName(a)),d;if((h=c[3])&&l.getElementsByClassName&&b.getElementsByClassName)return O.apply(d,b.getElementsByClassName(h)),d}if(l.qsa&&(!C||!C.test(a))){g=c=A;h=b;G=9===e&&a;if(1===e&&"object"!==b.nodeName.toLowerCase()){e=o(a);(c=b.getAttribute("id"))?g=c.replace(Na,
"\\$\x26"):b.setAttribute("id",g);g="[id\x3d'"+g+"'] ";for(h=e.length;h--;)e[h]=g+s(e[h]);h=na.test(a)&&W(b.parentNode)||b;G=e.join(",")}if(G)try{return O.apply(d,h.querySelectorAll(G)),d}catch(i){}finally{c||b.removeAttribute("id")}}}var j;a:{a=a.replace(fa,"$1");g=o(a);if(!f&&1===g.length){c=g[0]=g[0].slice(0);if(2<c.length&&"ID"===(j=c[0]).type&&l.getById&&9===b.nodeType&&H&&k.relative[c[1].type]){b=(k.find.ID(j.matches[0].replace(P,Q),b)||[])[0];if(!b){j=d;break a}a=a.slice(c.shift().value.length)}for(e=
ga.needsContext.test(a)?0:c.length;e--;){j=c[e];if(k.relative[h=j.type])break;if(h=k.find[h])if(f=h(j.matches[0].replace(P,Q),na.test(c[0].type)&&W(b.parentNode)||b)){c.splice(e,1);a=f.length&&s(c);if(!a){O.apply(d,f);j=d;break a}break}}}oa(a,g)(f,b,!H,d,na.test(a)&&W(b.parentNode)||b);j=d}return j},y=function(){function a(d,f){b.push(d+" ")>k.cacheLength&&delete a[b.shift()];return a[d+" "]=f}var b=[];return a},m=function(a){a[A]=!0;return a},v=function(a){var b=B.createElement("div");try{return!!a(b)}catch(d){return!1}finally{b.parentNode&&
b.parentNode.removeChild(b)}},X=function(a,b){for(var d=a.split("|"),f=a.length;f--;)k.attrHandle[d[f]]=b},ca=function(a,b){var d=b&&a,f=d&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||wa)-(~a.sourceIndex||wa);if(f)return f;if(d)for(;d=d.nextSibling;)if(d===b)return-1;return a?1:-1},T=function(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}},Y=function(a){return function(b){var d=b.nodeName.toLowerCase();return("input"===d||"button"===d)&&b.type===a}},D=function(a){return m(function(b){b=
+b;return m(function(d,f){for(var c,g=a([],d.length,b),h=g.length;h--;)if(d[c=g[h]])d[c]=!(f[c]=d[c])})})},W=function(a){return a&&typeof a.getElementsByTagName!==Z&&a},$=function(){},o=function(a,b){var d,f,c,g,h,e,G;if(h=xa[a+" "])return b?0:h.slice(0);h=a;e=[];for(G=k.preFilter;h;){if(!d||(f=Oa.exec(h)))f&&(h=h.slice(f[0].length)||h),e.push(c=[]);d=!1;if(f=Pa.exec(h))d=f.shift(),c.push({value:d,type:f[0].replace(fa," ")}),h=h.slice(d.length);for(g in k.filter)if((f=ga[g].exec(h))&&(!G[g]||(f=G[g](f))))d=
f.shift(),c.push({value:d,type:g,matches:f}),h=h.slice(d.length);if(!d)break}return b?h.length:h?p.error(a):xa(a,e).slice(0)},s=function(a){for(var b=0,d=a.length,f="";b<d;b++)f+=a[b].value;return f},K=function(a,b,d){var f=b.dir,c=d&&"parentNode"===f,g=Qa++;return b.first?function(b,d,g){for(;b=b[f];)if(1===b.nodeType||c)return a(b,d,g)}:function(b,d,e){var o,j,i,m=I+" "+g;if(e)for(;b=b[f];){if((1===b.nodeType||c)&&a(b,d,e))return!0}else for(;b=b[f];)if(1===b.nodeType||c)if(i=b[A]||(b[A]={}),(j=
i[f])&&j[0]===m){if(!0===(o=j[1])||o===J)return!0===o}else if(j=i[f]=[m],j[1]=a(b,d,e)||J,!0===j[1])return!0}},n=function(a){return 1<a.length?function(b,d,f){for(var c=a.length;c--;)if(!a[c](b,d,f))return!1;return!0}:a[0]},ha=function(a,b,d,f,c){for(var g,h=[],e=0,G=a.length,o=null!=b;e<G;e++)if(g=a[e])if(!d||d(g,f,c))h.push(g),o&&b.push(e);return h},pa=function(a,b,d,f,c,e){f&&!f[A]&&(f=pa(f));c&&!c[A]&&(c=pa(c,e));return m(function(h,e,g,o){var j,i,m=[],s=[],n=e.length,l;if(!(l=h)){l=b||"*";for(var k=
g.nodeType?[g]:g,r=[],u=0,v=k.length;u<v;u++)p(l,k[u],r);l=r}l=a&&(h||!b)?ha(l,m,a,g,o):l;k=d?c||(h?a:n||f)?[]:e:l;d&&d(l,k,g,o);if(f){j=ha(k,s);f(j,[],g,o);for(g=j.length;g--;)if(i=j[g])k[s[g]]=!(l[s[g]]=i)}if(h){if(c||a){if(c){j=[];for(g=k.length;g--;)if(i=k[g])j.push(l[g]=i);c(null,k=[],j,o)}for(g=k.length;g--;)if((i=k[g])&&-1<(j=c?U.call(h,i):m[g]))h[j]=!(e[j]=i)}}else k=ha(k===e?k.splice(n,k.length):k),c?c(null,e,k,o):O.apply(e,k)})},x=function(a){var b,d,c,t=a.length,g=k.relative[a[0].type];
d=g||k.relative[" "];for(var h=g?1:0,e=K(function(a){return a===b},d,!0),j=K(function(a){return-1<U.call(b,a)},d,!0),o=[function(a,d,c){return!g&&(c||d!==ia)||((b=d).nodeType?e(a,d,c):j(a,d,c))}];h<t;h++)if(d=k.relative[a[h].type])o=[K(n(o),d)];else{d=k.filter[a[h].type].apply(null,a[h].matches);if(d[A]){for(c=++h;c<t&&!k.relative[a[c].type];c++);return pa(1<h&&n(o),1<h&&s(a.slice(0,h-1).concat({value:" "===a[h-2].type?"*":""})).replace(fa,"$1"),d,h<c&&x(a.slice(h,c)),c<t&&x(a=a.slice(c)),c<t&&s(a))}o.push(d)}return n(o)},
z,l,J,k,ja,L,oa,ia,R,aa,N,B,M,H,C,V,ka,ba,A="sizzle"+-new Date,w=u.document,I=0,Qa=0,ya=y(),xa=y(),za=y(),qa=function(a,b){a===b&&(aa=!0);return 0},Z="undefined",wa=-2147483648,Ra={}.hasOwnProperty,S=[],Sa=S.pop,Ta=S.push,O=S.push,Aa=S.slice,U=S.indexOf||function(a){for(var b=0,d=this.length;b<d;b++)if(this[b]===a)return b;return-1},Ba="(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w#"),Ca="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?\x3d)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+
Ba+")|)|)[\\x20\\t\\r\\n\\f]*\\]",ra=":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\(((['\"])((?:\\\\.|[^\\\\])*?)\\3|((?:\\\\.|[^\\\\()[\\]]|"+Ca.replace(3,8)+")*)|.*)\\)|)",fa=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),Oa=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,Pa=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,Ua=RegExp("\x3d[\\x20\\t\\r\\n\\f]*([^\\]'\"]*?)[\\x20\\t\\r\\n\\f]*\\]","g"),Va=RegExp(ra),Wa=RegExp("^"+Ba+"$"),ga={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,
CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:RegExp("^("+"(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w*")+")"),ATTR:RegExp("^"+Ca),PSEUDO:RegExp("^"+ra),CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)","i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$",
"i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[\x3e+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?\x3d[^-]|$)","i")},Xa=/^(?:input|select|textarea|button)$/i,Ya=/^h\d$/i,da=/^[^{]+\{\s*\[native \w/,Ma=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,na=/[+~]/,Na=/'|\\/g,P=RegExp("\\\\([\\da-f]{1,6}[\\x20\\t\\r\\n\\f]?|([\\x20\\t\\r\\n\\f])|.)","ig"),Q=function(a,b,d){a="0x"+b-65536;return a!==a||d?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>
10|55296,a&1023|56320)};try{O.apply(S=Aa.call(w.childNodes),w.childNodes),S[w.childNodes.length].nodeType}catch(hb){O={apply:S.length?function(a,b){Ta.apply(a,Aa.call(b))}:function(a,b){for(var d=a.length,c=0;a[d++]=b[c++];);a.length=d-1}}}l=p.support={};L=p.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};N=p.setDocument=function(a){var b=a?a.ownerDocument||a:w;a=b.defaultView;if(b===B||9!==b.nodeType||!b.documentElement)return B;B=b;M=b.documentElement;
H=!L(b);a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){N()},!1):a.attachEvent&&a.attachEvent("onunload",function(){N()}));l.attributes=v(function(a){a.className="i";return!a.getAttribute("className")});l.getElementsByTagName=v(function(a){a.appendChild(b.createComment(""));return!a.getElementsByTagName("*").length});l.getElementsByClassName=da.test(b.getElementsByClassName)&&v(function(a){a.innerHTML="\x3cdiv class\x3d'a'\x3e\x3c/div\x3e\x3cdiv class\x3d'a i'\x3e\x3c/div\x3e";
a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});l.getById=v(function(a){M.appendChild(a).id=A;return!b.getElementsByName||!b.getElementsByName(A).length});l.getById?(k.find.ID=function(a,b){if(typeof b.getElementById!==Z&&H){var c=b.getElementById(a);return c&&c.parentNode?[c]:[]}},k.filter.ID=function(a){var b=a.replace(P,Q);return function(a){return a.getAttribute("id")===b}}):(delete k.find.ID,k.filter.ID=function(a){var b=a.replace(P,Q);return function(a){return(a=
typeof a.getAttributeNode!==Z&&a.getAttributeNode("id"))&&a.value===b}});k.find.TAG=l.getElementsByTagName?function(a,b){if(typeof b.getElementsByTagName!==Z)return b.getElementsByTagName(a)}:function(a,b){var c,g=[],h=0,e=b.getElementsByTagName(a);if("*"===a){for(;c=e[h++];)1===c.nodeType&&g.push(c);return g}return e};k.find.CLASS=l.getElementsByClassName&&function(a,b){if(typeof b.getElementsByClassName!==Z&&H)return b.getElementsByClassName(a)};V=[];C=[];if(l.qsa=da.test(b.querySelectorAll))v(function(a){a.innerHTML=
"\x3cselect t\x3d''\x3e\x3coption selected\x3d''\x3e\x3c/option\x3e\x3c/select\x3e";a.querySelectorAll("[t^\x3d'']").length&&C.push("[*^$]\x3d[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||C.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");a.querySelectorAll(":checked").length||C.push(":checked")}),v(function(a){var c=b.createElement("input");c.setAttribute("type",
"hidden");a.appendChild(c).setAttribute("name","D");a.querySelectorAll("[name\x3dd]").length&&C.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?\x3d");a.querySelectorAll(":enabled").length||C.push(":enabled",":disabled");a.querySelectorAll("*,:x");C.push(",.*:")});(l.matchesSelector=da.test(ka=M.webkitMatchesSelector||M.mozMatchesSelector||M.oMatchesSelector||M.msMatchesSelector))&&v(function(a){l.disconnectedMatch=ka.call(a,"div");ka.call(a,"[s!\x3d'']:x");V.push("!\x3d",ra)});C=C.length&&RegExp(C.join("|"));
V=V.length&&RegExp(V.join("|"));ba=(a=da.test(M.compareDocumentPosition))||da.test(M.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,g=b&&b.parentNode;return a===g||!(!g||!(1===g.nodeType&&(c.contains?c.contains(g):a.compareDocumentPosition&&a.compareDocumentPosition(g)&16)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};qa=a?function(a,c){if(a===c)return aa=!0,0;var e=!a.compareDocumentPosition-!c.compareDocumentPosition;if(e)return e;e=(a.ownerDocument||a)===
(c.ownerDocument||c)?a.compareDocumentPosition(c):1;return e&1||!l.sortDetached&&c.compareDocumentPosition(a)===e?a===b||a.ownerDocument===w&&ba(w,a)?-1:c===b||c.ownerDocument===w&&ba(w,c)?1:R?U.call(R,a)-U.call(R,c):0:e&4?-1:1}:function(a,c){if(a===c)return aa=!0,0;var e,g=0;e=a.parentNode;var h=c.parentNode,o=[a],j=[c];if(!e||!h)return a===b?-1:c===b?1:e?-1:h?1:R?U.call(R,a)-U.call(R,c):0;if(e===h)return ca(a,c);for(e=a;e=e.parentNode;)o.unshift(e);for(e=c;e=e.parentNode;)j.unshift(e);for(;o[g]===
j[g];)g++;return g?ca(o[g],j[g]):o[g]===w?-1:j[g]===w?1:0};return b};p.matches=function(a,b){return p(a,null,null,b)};p.matchesSelector=function(a,b){(a.ownerDocument||a)!==B&&N(a);b=b.replace(Ua,"\x3d'$1']");if(l.matchesSelector&&H&&(!V||!V.test(b))&&(!C||!C.test(b)))try{var d=ka.call(a,b);if(d||l.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(c){}return 0<p(b,B,null,[a]).length};p.contains=function(a,b){(a.ownerDocument||a)!==B&&N(a);return ba(a,b)};p.attr=function(a,b){(a.ownerDocument||
a)!==B&&N(a);var d=k.attrHandle[b.toLowerCase()],d=d&&Ra.call(k.attrHandle,b.toLowerCase())?d(a,b,!H):void 0;return void 0!==d?d:l.attributes||!H?a.getAttribute(b):(d=a.getAttributeNode(b))&&d.specified?d.value:null};p.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};p.uniqueSort=function(a){var b,d=[],c=0,e=0;aa=!l.detectDuplicates;R=!l.sortStable&&a.slice(0);a.sort(qa);if(aa){for(;b=a[e++];)b===a[e]&&(c=d.push(e));for(;c--;)a.splice(d[c],1)}R=null;return a};ja=p.getText=
function(a){var b,d="",c=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)d+=ja(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[c++];)d+=ja(b);return d};k=p.selectors={cacheLength:50,createPseudo:m,match:ga,attrHandle:{},find:{},relative:{"\x3e":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(P,
Q);a[3]=(a[4]||a[5]||"").replace(P,Q);"~\x3d"===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||p.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&p.error(a[0]);return a},PSEUDO:function(a){var b,d=!a[5]&&a[2];if(ga.CHILD.test(a[0]))return null;if(a[3]&&void 0!==a[4])a[2]=a[4];else if(d&&Va.test(d)&&(b=o(d,!0))&&(b=d.indexOf(")",d.length-b)-d.length))a[0]=a[0].slice(0,
b),a[2]=d.slice(0,b);return a.slice(0,3)}},filter:{TAG:function(a){var b=a.replace(P,Q).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=ya[a+" "];return b||(b=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&ya(a,function(a){return b.test("string"===typeof a.className&&a.className||typeof a.getAttribute!==Z&&a.getAttribute("class")||"")})},ATTR:function(a,b,d){return function(c){c=p.attr(c,a);if(null==
c)return"!\x3d"===b;if(!b)return!0;c+="";return"\x3d"===b?c===d:"!\x3d"===b?c!==d:"^\x3d"===b?d&&0===c.indexOf(d):"*\x3d"===b?d&&-1<c.indexOf(d):"$\x3d"===b?d&&c.slice(-d.length)===d:"~\x3d"===b?-1<(" "+c+" ").indexOf(d):"|\x3d"===b?c===d||c.slice(0,d.length+1)===d+"-":!1}},CHILD:function(a,b,d,c,e){var g="nth"!==a.slice(0,3),h="last"!==a.slice(-4),o="of-type"===b;return 1===c&&0===e?function(a){return!!a.parentNode}:function(b,d,j){var i,k,m,l,s;d=g!==h?"nextSibling":"previousSibling";var n=b.parentNode,
p=o&&b.nodeName.toLowerCase();j=!j&&!o;if(n){if(g){for(;d;){for(k=b;k=k[d];)if(o?k.nodeName.toLowerCase()===p:1===k.nodeType)return!1;s=d="only"===a&&!s&&"nextSibling"}return!0}s=[h?n.firstChild:n.lastChild];if(h&&j){j=n[A]||(n[A]={});i=j[a]||[];l=i[0]===I&&i[1];m=i[0]===I&&i[2];for(k=l&&n.childNodes[l];k=++l&&k&&k[d]||(m=l=0)||s.pop();)if(1===k.nodeType&&++m&&k===b){j[a]=[I,l,m];break}}else if(j&&(i=(b[A]||(b[A]={}))[a])&&i[0]===I)m=i[1];else for(;k=++l&&k&&k[d]||(m=l=0)||s.pop();)if((o?k.nodeName.toLowerCase()===
p:1===k.nodeType)&&++m)if(j&&((k[A]||(k[A]={}))[a]=[I,m]),k===b)break;m-=e;return m===c||0===m%c&&0<=m/c}}},PSEUDO:function(a,b){var d,c=k.pseudos[a]||k.setFilters[a.toLowerCase()]||p.error("unsupported pseudo: "+a);return c[A]?c(b):1<c.length?(d=[a,a,"",b],k.setFilters.hasOwnProperty(a.toLowerCase())?m(function(a,d){for(var e,j=c(a,b),o=j.length;o--;)e=U.call(a,j[o]),a[e]=!(d[e]=j[o])}):function(a){return c(a,0,d)}):c}},pseudos:{not:m(function(a){var b=[],d=[],c=oa(a.replace(fa,"$1"));return c[A]?
m(function(a,b,d,e){e=c(a,null,e,[]);for(var j=a.length;j--;)if(d=e[j])a[j]=!(b[j]=d)}):function(a,e,h){b[0]=a;c(b,null,h,d);return!d.pop()}}),has:m(function(a){return function(b){return 0<p(a,b).length}}),contains:m(function(a){return function(b){return-1<(b.textContent||b.innerText||ja(b)).indexOf(a)}}),lang:m(function(a){Wa.test(a||"")||p.error("unsupported lang: "+a);a=a.replace(P,Q).toLowerCase();return function(b){var d;do if(d=H?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return d=
d.toLowerCase(),d===a||0===d.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(a){var b=u.location&&u.location.hash;return b&&b.slice(1)===a.id},root:function(a){return a===M},focus:function(a){return a===B.activeElement&&(!B.hasFocus||B.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&
!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!k.pseudos.empty(a)},header:function(a){return Ya.test(a.nodeName)},input:function(a){return Xa.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===
a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:D(function(){return[0]}),last:D(function(a,b){return[b-1]}),eq:D(function(a,b,d){return[0>d?d+b:d]}),even:D(function(a,b){for(var d=0;d<b;d+=2)a.push(d);return a}),odd:D(function(a,b){for(var d=1;d<b;d+=2)a.push(d);return a}),lt:D(function(a,b,d){for(b=0>d?d+b:d;0<=--b;)a.push(b);return a}),gt:D(function(a,b,d){for(d=0>d?d+b:d;++d<b;)a.push(d);return a})}};k.pseudos.nth=k.pseudos.eq;for(z in{radio:!0,checkbox:!0,file:!0,password:!0,
image:!0})k.pseudos[z]=T(z);for(z in{submit:!0,reset:!0})k.pseudos[z]=Y(z);$.prototype=k.filters=k.pseudos;k.setFilters=new $;oa=p.compile=function(a,b){var d,c=[],e=[],g=za[a+" "];if(!g){b||(b=o(a));for(d=b.length;d--;)g=x(b[d]),g[A]?c.push(g):e.push(g);var h=0,j=0<c.length,i=0<e.length;d=function(a,b,d,g,o){var m,l,s,n=0,r="0",u=a&&[],v=[],w=ia,K=a||i&&k.find.TAG("*",o),y=I+=null==w?1:Math.random()||0.1,x=K.length;o&&(ia=b!==B&&b,J=h);for(;r!==x&&null!=(m=K[r]);r++){if(i&&m){for(l=0;s=e[l++];)if(s(m,
b,d)){g.push(m);break}o&&(I=y,J=++h)}j&&((m=!s&&m)&&n--,a&&u.push(m))}n+=r;if(j&&r!==n){for(l=0;s=c[l++];)s(u,v,b,d);if(a){if(0<n)for(;r--;)!u[r]&&!v[r]&&(v[r]=Sa.call(g));v=ha(v)}O.apply(g,v);o&&(!a&&0<v.length&&1<n+c.length)&&p.uniqueSort(g)}o&&(I=y,ia=w);return u};d=j?m(d):d;g=za(a,d)}return g};l.sortStable=A.split("").sort(qa).join("")===A;l.detectDuplicates=!!aa;N();l.sortDetached=v(function(a){return a.compareDocumentPosition(B.createElement("div"))&1});v(function(a){a.innerHTML="\x3ca href\x3d'#'\x3e\x3c/a\x3e";
return"#"===a.firstChild.getAttribute("href")})||X("type|href|height|width",function(a,b,d){if(!d)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});(!l.attributes||!v(function(a){a.innerHTML="\x3cinput/\x3e";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")}))&&X("value",function(a,b,d){if(!d&&"input"===a.nodeName.toLowerCase())return a.defaultValue});v(function(a){return null==a.getAttribute("disabled")})||X("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",
function(a,b,d){var c;if(!d)return!0===a[b]?b.toLowerCase():(c=a.getAttributeNode(b))&&c.specified?c.value:null});"function"===typeof r&&r.amd?r(function(){return p}):"undefined"!==typeof module&&module.exports?module.exports=p:u.Sizzle=p;var Za=c,Da,la,E={},$a=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);c.each($a,function(a){la=(/[\/ :]([^\/ :]+)$/.exec(a)||[])[1];E[la?a.substr(0,a.length-la.length-1).replace(/\d*$/,
""):a]=la||!0});Da={aol:E.aol,blackberry:E.blackberry,ie:E.msie,ios:E.mobile&&E.safari,opera:E.opera,playstation:E.playstation,version:parseFloat(E.version||E.crios||E.msie)||!1};Za.browser=Da;var ab={bbp:{id_finder:["div",/^post-(\d+)$/],scope:"li .post"},hdlr:{id_finder:["div",/^post_(\d+)$/],scope:".post-content-area"},ipb:{id_finder:["div",/^post_id_(\d+)$/],scope:".post_body .post"},phpb:{id_finder:["div.post",/^p(\d+)$/],scope:".postbody .content,.postbody .signature"},ubb:{id_finder:["a",/^Post(\d+)$/,
"name"],scope:".post_inner *[id^\x3d'body'],.post_inner .signature"},vb3:{id_finder:["div[id], table[id]",/^post(\d+)$/],scope:"td[id^\x3d'td_post_'] div[id^\x3d'post_message_'],td[id^\x3d'td_post_'] div[id^\x3d'post_message_'] ~ div:not([class])"},vb4:{id_finder:["li",/^post_(\d+)$/],scope:".post-content,.postbody .content,.postbody .signature,ul.conversation-list .list-item-body"},wppr:{id_finder:["div",/^post-(\d+)$/],scope:null}};c.platforms=function(a){return c.extend(ab[a]||{},{getPostIDs:function(){var a=
[],d=this.id_finder;d&&c.each(c.select(d[0]),function(c){var e=d[2]||"id";(c=c[e]?c[e].match(d[1]):null)&&a.push(c[1])});return a.length?a:null}})};c.traits={basicCompatibility:!(c.browser.blackberry||c.browser.playstation),cors:window.XMLHttpRequest&&void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!c.browser.ios,jsRedirectSetsReferrer:c.browser.aol||!(c.browser.ie||c.browser.opera),quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};
var j,ea,F,bb=function(a){var b=a.previousSibling,d=a.nextSibling,f=["",a.textContent,""],j=function(a,b){for(var c=a,d=c.data;(c=c[b+"Sibling"])&&3===c.nodeType;)d+=c.data;return d},g=function(a,b,c){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");c=c.replace(/\s+/g," ");a=a.replace(/^\s+/,"");" "===b.substr(0,1)&&(b=b.substr(1),a+=" "!==a.substr(a.length-1,1)?" ":"");" "===b.substr(b.length-1,1)&&(b=b.substr(0,b.length-1),c=(" "!==c.substr(0,1)?" ":"")+c);c=c.replace(/\s+$/,"");return[a,b,c]};void 0!==
f[1]&&(f[0]=b&&3===b.nodeType?j(b,"previous"):"",f[2]=d&&3===d.nodeType?j(d,"next"):"",f=g.apply(this,f),""!==f[0]&&""!==f[2]&&(f[0]=f[0].split(" ").reverse().slice(0,10+(" "===f[0].substr(f[0].length-1,1)?1:0)).reverse().join(" "),f[2]=f[2].split(" ").slice(0,10).join(" "),a={type:"context",itype:(c.cache(a,"params")||{}).type,before:f[0],after:f[2],txt:f[1],loc:location.href,out:c.getActualHref(a),v:2},e.log("info",c.toQuery(a))))},Ea={};c.harmony={UNSAFE_QUIRKSMODE_HANDLERS:0,LINK_LEVEL_EVENTS:-1};
var cb=c.exceptionLogger(function(){var a=!0===window.document.__v5k;window.document.__v5k=!0;a||(this.initLibEvents(),this.initNamespace(),this.initOptions(),c.exceptionLogger(c.bind(this.logException,this),!j.dev),this.initProcessors(),this.initDRApi(),this.initApi(),this.enabled()&&(this.initLegacyCallbacks(),this.ping()))}),sa=[],ta,Fa=1,ma={},db={product_widget:"spotlight"},ua=function(){var a=!1,b={},d=function(a){return function(){if(a){var b=c.toArray(arguments);b.unshift("custom",a);e.log.apply(this,
b)}}};ta=null;c.each(ma,function(f,j){j=db[j]||j;f.setup=f.setup||window.vglnk&&window.vglnk[j+"_plugin"];f.setup?(!f.run&&"function"===c.type(f.setup)&&(f.run=f.setup(f.opts,c.clone(c),F,d(f.opts.key))||c.noop),f.opts.mode===e.PLUGIN_MANUAL?b[j]=f:f.run()):(a=!0,b[j]=f)});ma=b;a&&(ta=setTimeout(c.exceptionLogger(ua),Math.min(Math.max(Math.pow(2,++Fa),100),5E3)))},eb=function(a){return function(){delete ma[a].opts.mode;Fa=1;clearTimeout(ta);ua()}},fb=c.canonicalizeHostname(document.location),gb=c.generateNodeFilter({rels:["norewrite",
"noskim"],custom:function(a){var b,d="";try{b=a.hostname,d=a.protocol,b.charAt(0)}catch(f){return!0}""!==b&&(b=c.canonicalizeHostname(a));return""===b||fb===b||!d.match(/^https?:$/i)||j.norewrite[b]||!(j.rewrite_original||c.cache(a,"type"))}}),Ga,Ha=!1,Ia={},Ja=!1,Ka=[],La=function(a){if(void 0===a)return Ka;"function"===c.type(a)&&(Ka.push({id:c.uniqid(),fn:a}),Ja&&this.initLinks())};La(function(){Ja=!0});e={PLUGIN_MANUAL:1,api:function(a,b,d){a=j.api_url+"/"+a;b=c.extend({cuid:j.cuid,key:j.key,
drKey:j.key?null:j.dr_key,loc:location.href,subId:j.sub_id,v:1},b);b.subId&&b.key!==j.key&&(b.subId=null);return c.request(a,b,d)},addEventListener:function(a,b){this.fire(a,b)},click:function(a,b){var d,f,e,g,h=c.context(a)||window;b=a.target||b;b=!b||b===h.name||"_top"===b&&h.top===h||"_parent"===b&&h.parent===h?"_self":b;"_self"===b?e=h:c.traits.crossWindowCommunication&&c.traits.jsRedirectSetsReferrer?(f=h.open("",b),f.focus(),e=f):e=void 0;if("_self"!==b&&(!c.traits.crossWindowCommunication||
!c.traits.jsRedirectSetsReferrer))g="go";else try{if(void 0===e.document)throw!0;g="jsonp"}catch(o){g="go"}d=c.destructing(c.bind(function(){j.time_click&&arguments.length&&this.logTime("clk");var d=c.toArray(arguments);d.unshift(a,e,b);this.onApiClick.apply(this,d)},this));c.cache(this,"link","string"===typeof a?a:c.getActualHref(a));if("string"===typeof a&&(a=c.createA(a,b),!this.processLink(a))||!j.enabled)return d();f=this.clickParams(a,g);this.logTime();j.log_context&&bb(a);if("go"===g)this.redirect(this.api("click",
f,{"return":!0}),h,e,b);else if(e===h)this.api("click",f,{fn:d,timeout:j.click_timeout});else{if(c.contextIsAncestor(h,e))return this.redirect(c.getActualHref(a),h,e,b);d=c.exceptionLogger(d);setTimeout(function(){d()},j.click_timeout);e.document.open();e.callback=d;e.document.write("\x3chtml\x3e\x3chead\x3e\x3ctitle\x3e"+c.getActualHref(a)+'\x3c/title\x3e\x3cscript type\x3d"text/javascript" src\x3d"'+this.api("click",f,{fn:"callback","return":!0})+'"\x3e\x3c/script\x3e\x3c/head\x3e\x3c/html\x3e');
e.document.close()}},clickParams:function(a,b){var d=c.extend(c.cache(a,"params"),{format:b,libId:j.library_id,out:c.getActualHref(a),ref:window.document.referrer||null,reaf:j.reaffiliate||null,title:window.document.title,txt:a.innerHTML});128<d.txt.length&&(d.txt=d.txt.replace(/<[^>]+>/g,""),d.txt=128<d.txt.length?d.txt.substr(0,125)+"...":d.txt);return d},enabled:function(){if(j.enabled&&ea!==window&&window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))j.enabled=!1;return j.enabled},
expose:function(a,b){if(b=b||this[a])"function"===typeof b?b=c.exceptionLogger(c.bind(b,this)):"object"===typeof b&&(b=c.clone(b)),F[a]||(F[a]=b)},fire:function(a,b){a=a.toLowerCase();var d=Ea[a]||{fired:!1,listeners:[]};"function"===typeof b?d.fired?b({type:a}):d.listeners.push(b):(d.fired=!0,c.each(d.listeners,function(b){"function"===typeof b&&b({type:a})}),d.listeners=[]);Ea[a]=d},handleRightClick:function(a,b){if(j.rewrite_modified&&a&&b)switch(b){case "setup":c.cache(a,"href")||c.cache(a,"href",
a.href);a.href=this.api("click",this.clickParams(a,"go"),{"return":!0});setTimeout(c.exceptionLogger(c.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":a.href=c.cache(a,"href"),c.cache(a,"href",null)}},harmony:function(a){return j.harmony_level<=a},init:cb,initApi:function(){var a,b={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(b[a]=window.vglnk[a]);F=ea[i]=c.noop;this.expose("click");this.expose("link",function(a){"element"===c.type(a)&&a.href&&
(e.initContext(c.context(a)),e.processLink(a))});this.expose("$",c.clone(c));this.expose("api");this.expose("opt");this.expose("registerProcessor",function(){if(0<arguments.length)return e.registerProcessor.apply(e,arguments)});c.extend(F,F===window.vglnk?b:{})},initContext:function(a){if(void 0===a)return sa;a&&!c.contains(sa,a)&&(sa.push(a),this.initLinks(a),this.initEvents(a))},initDRApi:function(){var a=!1;window.DrivingRevenue=c.exceptionLogger(c.destructing(c.bind(function(){a=!0;j.dr_key=window.DR_id;
this.enabled()&&this.ping()},this)));c.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(b){window.DrivingRevenue=void 0}})},initEvents:function(a){var b={left:e.onClick,right:e.onContextmenu},d={left:c.noop,right:c.noop},f=c.traits.windowLevelHandlers?a:a.document,j=function(f){f=f||a.event;if((f=c.eventLink(f))&&!c.cache(f,"evented"))g(f,e.harmony(c.harmony.LINK_LEVEL_EVENTS)?b:d),c.cache(f,"evented",!0)},g=function(a,b){c.on(a,"click",c.bind(b.left,e));c.on(a,"contextmenu",
c.bind(b.right,e))};c.on(f,"copy",c.bind(e.onCopy,e));c.on(f,"mousedown",j);if(e.harmony(c.harmony.LINK_LEVEL_EVENTS))c.on("DOMReady",function(){c.each(a.document.links,function(a){c.on(a,"mousedown",j)})});(!c.traits.quirksMode||e.harmony(c.harmony.UNSAFE_QUIRKSMODE_HANDLERS))&&g(f,b)},initLegacyOptions:function(){var a,b={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in b)void 0!==window[a]&&(F[b[a]]=window[a],"vglnk_domain"===
a&&(F[b[a]]+="/api"))},initLegacyCallbacks:function(){var a,b={vl_cB:c.bind(this.onApiClick,this),vl_disable:function(){j.enabled=!1}};for(a in b)window[a]=b[a]},initLibEvents:function(){c.on(e);c.ready(c.bind(function(){this.fire("DOMReady")},this))},initLinks:function(a){var b=c.bind(function(a){c.each(c.toArray(a.document.links),c.bind(this.processLink,this))},this);void 0===a?c.each(this.initContext(),b):b(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(i="vglnk");var a=window,b=
i.split("."),c;for(i=b.pop();0<b.length;)c=b.shift(),a[c]=a[c]||{},a=a[c];ea=a;F=ea[i]=ea[i]||{}},initOptions:function(){var a;this.initLegacyOptions();j=c.extend(this.publicOptions({api_url:"//api.viglink.com/api",asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:c.traits.basicCompatibility,key:null,partner:null,sub_id:null,reaffiliate:!1,harmony_level:0,rewrite_original:!0,rewrite_modified:!1}),j,F,{click_timeout:1E3,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,nofollow:{},
norewrite:{},plugins:{link_affiliation:{},modified_clicks:{},partner_integration:{}},time_click:!1,time_ping:!1,testing_js:[]});for(a in j)"_plugin"===a.substr(-7)&&delete j[a]},initPlugins:function(a){for(var b in a)"object"===typeof a[b]&&!1!==a[b].enabled&&(ma[b]={opts:a[b]},a[b].mode===this.PLUGIN_MANUAL&&this.expose("init_"+b,eb(b)));ua()},initProcessors:function(){this.registerProcessor(function(a){var b;b=c.createA(j.api_url);if("/api/click"===a.pathname&&(a.hostname===b.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))b=
c.fromQuery(a.search),void 0!==b.out&&(a.href=b.out,delete b.out,c.cache(a,"params",b))});this.registerProcessor(function(a){j.nofollow[a.href]&&!c.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&c.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target="_blank")})},isRewritable:function(a){return gb(a,{ancestors:!1})},log:function(a,b,d,f){var e,g=
c.toQuery({nocache:c.uniqid()});e="pixel.gif";if("custom"===a)g+="\x26"+c.toQuery({key:b,type:d}),c.each("array"===c.type(f)?f:[f],function(a){c.each(["e","i","o"],function(b){delete a[b]});g+="\x26"+c.toQuery(a)});else{g+="\x26"+c.toQuery({key:j.key,drKey:j.key?null:j.dr_key});if("time"===a)e="time.gif",a={libId:j.library_id,time:d,type:b};else if("exception"===a)a={e:b,o:d};else if("info"===a)a={i:b};else return;g+="\x26"+c.toQuery(a)}e=j.api_url+"/"+e+"?"+g;c.transmitsPII(e)||(c.createEl("img").src=
e)},logException:function(a){if(j.debug){var b={link:c.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?b.message=a:b=c.extend(b,a);this.log("exception",a,c.toQuery(b))}},logTime:function(a){0===arguments.length?Ga=(new Date).getTime():this.log("time",a,(new Date).getTime()-Ga)},onApiClick:function(a,b,d,e,o){var g=e||c.getActualHref(a),h=c.bind(function(){this.redirect(g,c.context(a),b,d)},this);"object"===typeof o&&(o.tracking||o.image)?(e=c.createEl(o.tracking?
"iframe":"img",{src:o.tracking||o.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(e),setTimeout(c.exceptionLogger(h),o.timeout||j.hop_timeout)):h()},onApiPing:function(a,b,d,f,o,g){j.rewrite_original=!1;o=c.reformatKeys(o||{});var h,i;f=function(a){var b={},d=function(a){c.isArray(a)?b[a[0]]=a[1]:b[a]=1};c.isArray(a)&&c.each(a,d);return b};i=c.extend(j.plugins,o.plugins);j=c.extend(j,o);delete j.plugins;j.library_id=a;j.click_timeout=b;j.time_ping&&this.logTime("png");"array"===
c.type(j.testing_js)&&0<j.testing_js.length&&c.each(j.testing_js,function(a){c.jsonp(a)});c.extend(j.norewrite,f(d));c.extend(j.nofollow,f(g));for(h in j)"on"===h.toLowerCase().substr(0,2)&&(2<h.length&&"function"===c.type(j[h]))&&(c.on(e,h.toLowerCase().substr(2),c.bind(j[h],window)),delete j[h]);this.initPlugins(i);this.initContext(window);this.fire("libready")},onClick:function(a){a=a||window.event;var b=a.ctrlKey||a.metaKey||a.altKey||a.shiftKey,d=a.which&&1===a.which||0===a.button,e=c.eventLink(a);
if(e&&this.isRewritable(e)&&!b&&d&&!c.isDefaultPrevented(a))return this.click(e),c.preventDefault(a)},onContextmenu:function(a){(a=c.eventLink(a||window.event))&&this.isRewritable(a)&&this.handleRightClick(a,"setup")},onCopy:function(){var a,b,d,f,j=[];if(window.getSelection){d=window.getSelection();a=0;for(b=d.rangeCount;a<b;a++){try{f=d.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(g){}0<f.length&&128>=f.length&&j.push(f)}}c.each(j,function(a){e.log("info",
c.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,b){void 0!==b&&void 0!==this.publicOptions()[a]&&(j[a]=b);return j[a]},ping:function(){if(!Ha&&(j.key||j.dr_key)){var a={ref:document.referrer||null};Ha=!0;c.transmitsPII(this.api("ping",a,{"return":!0}))||(this.logTime(),this.api("ping",a,{fn:c.bind(this.onApiPing,this)}))}},processLink:function(a){if(this.isRewritable(a)){var b=c.cache(a,"processors")||{};c.each(this.registerProcessor(),function(c){b[c.id]||c.fn(a);b[c.id]=
!0});c.cache(a,"processors",b);return a}},publicOptions:function(a){"object"===c.type(a)&&(Ia=a);return c.extend({},Ia)},redirect:function(a,b,d,e){!c.traits.crossWindowCommunication&&!d?(e=b.open(a,e),e.focus()):c.traits.jsRedirectSetsReferrer?setTimeout(c.exceptionLogger(function(){!d||d===b?b.location=a:c.contextIsAncestor(b,d)?d.location=a:d.location.replace(a)}),0):("_blank"===e&&(e=c.uniqid("win_")),e=c.createA(a,e),e.rel="norewrite",b.document.body.appendChild(e),e.click(),e.parentNode.removeChild(e))},
registerProcessor:La};e.init();try{delete window.vglnk_self}catch(ib){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};window.vglnk.link_affiliation_plugin=function(i,e,q){return function(){q.opt("rewrite_original",!0)}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(i,e,q){return function(){q.opt("rewrite_modified",!0)}};window.vglnk=window.vglnk||{};
window.vglnk.partner_integration_plugin=function(i,e){var q="https:"===document.location.protocol,c={setup:function(){window._comscore=window._comscore||[]},run:function(){var c=window._comscore;c&&"function"===e.type(c.push)&&(c.push({c1:8,c2:17570528,c3:1}),e.jsonp("//"+(q?"sb":"b")+".scorecardresearch.com/beacon.js"))}};c.setup();return function(){c.run()}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(i,e,q){i=e.extend({key:null},i);var c={init:function(){e.each(this.getDRSearchForms(),function(i){if(!e.cache(i,"evented")){var u=c.getInput(i),p=function(){u.value||e.css(u,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};e.cache(i,"evented",!0);i.onsubmit=null;u.onfocus=null;u.onblur=null;e.on(u,"focus",function(){e.css(u,{"background-image":"none"})});e.on(u,"blur",p);p();e.on(i,"submit",function(e){c.onSubmit(e,i)})}})},
getDRSearchForms:function(){var i=[];e.each(document.getElementsByTagName("form"),function(e){c.getInput(e)&&e.id.match(/^DR-ebay-search(CSS|2)?$/i)&&i.push(e)});return i},getInput:function(c){return c.p||c.q2},onSubmit:function(r,u){r=r||window.event;var p="http://shop.ebay.com/i.html?"+e.toQuery({_nkw:c.getInput(u).value}),p=e.createA(p,"_blank");e.cache(p,"params",{key:i.key});q.click(p);return e.preventDefault(r)}};return function(){i.key&&(c.init(),e.on("DOMReady",e.bind(c.init,c)))}};
window.vglnk=window.vglnk||{};
window.vglnk.link_optimization_plugin=function(i,e,q){var c,r={};i=e.extend({platform:null},i);var u=function(c){var i=c.textContent||c.innerText;c=e.canonicalizeHostname(c);i=e.createEl("a",{href:i});return e.canonicalizeHostname(i)===c},p=e.generateNodeFilter({classes:["nooptimize"],rels:["nooptimize"],custom:function(c,i){return i?Boolean(e.cache(c,"type")):!1}}),y={data:!1,timing:!1};c={getLinks:function(){var m=e.platforms(i.platform).getPostIDs();q.api("optimize",{pt:i.platform,i:m?m.join("|"):
null,u:location.href},{fn:e.bind(c.onOptimizeApi,c)})},onOptimizeApi:function(c){"object"===e.type(c)&&"object"===e.type(c.optLinks)&&(r=c.optLinks,this.optimizeLinks({data:!0}))},optimizeLink:function(c){var i=r[c.href];if(i&&p(c)){var y=c.textContent||c.innerText,q;if(!(q=c.href===y))u(c)?(q=e.fromQuery(c.search),q=e.find(q,function(c){return c===y})):q=!1;if(q){q=i.optLink;for(var T;T=c.firstChild;)c.removeChild(T);c.appendChild(document.createTextNode(q))}else if(u(c))return;e.cache(c,"params",
{type:"LO",origOutId:i.pcid+":"+i.linkId});c.href=i.optLink}},optimizeLinks:function(i){y=e.extend(y,i);y.timing&&(y.data&&r)&&q.registerProcessor(e.bind(this.optimizeLink,c))},setup:function(){if(!i.platform||"full"===i.platform)this.getLinks();else e.on("DOMReady",e.bind(this.getLinks,this))}};c.setup();return function(){e.on("DOMReady",function(){c.optimizeLinks({timing:!0})})}};window.vglnk=window.vglnk||{};
window.vglnk.page_harmony_plugin=function(i,e,q){i=e.extend({level:null},i);return function(){var c=parseInt(i.level,10);isFinite(c)&&q.opt("harmony_level",c)}};window.vglnk=window.vglnk||{};
window.vglnk.product_linker_plugin=function(i,e,q,c){var r,u,p=null,y={},m,v=0,X=0,ca=0,T=0;i=e.extend({cat:null,platform:null,key:null,link_phrases:!0,link_urls:!0,link_target:null,per_page:null,per_phrase:5,product_source:null,proximity:null,same_proximity:100,scope:null,type:null,ui:!0},i);if(i.key){r=e.platforms(i.platform);var Y={data:i.link_phrases?!1:i.link_urls,timing:!1},D=function(c){var s=!1,p=c.parentNode;c.data&&(s=m.test(c.data.replace(/\s+/," ")));if(s)for(var n=c,q,r,x,s=function(c,
o){var k,l,s,n,m,p,q,u,r,K,x=function(e){r.parentNode.insertBefore(c,r);r.parentNode.removeChild(r);return e};r=e.createEl("span");c.parentNode.insertBefore(r,c);r.appendChild(c);K=e.geometry(r);if(i.proximity||i.same_proximity)for(p in y)if((q=y[p].links)&&!(y[p]===o&&!i.same_proximity||y[p]!==o&&!i.proximity)){u=y[p]===o?Math.max(i.same_proximity,i.proximity):i.proximity;k=0;for(l=q.length;k<l;k++){m=q[k].segments;s=0;for(n=m.length;s<n;s++){var w=m[s].geometry,v=K,z=u,w=e.extend({},w);w.x1-=z;
w.y1-=z;w.x2+=z;w.y2+=z;if(w.x1<v.x2&&w.x2>v.x1&&w.y1<v.y2&&w.y2>v.y1)return x(!1)}}}return x(!0)};n&&n.data&&(Boolean(r=n.data.match(/^\s+/))||Boolean(r=n.data.match(m)));){q=r[0];x=r.slice(1).join("");c=y[x.toLowerCase()];q=n.data.indexOf(q)+q.length-x.length;0<q&&(n=n.splitText(q));q=n.length<=x.length?null:n.splitText(x.length);x&&!c&&(c={url:x.match(/^https?:\/\//i)?x:"http://"+x,type:"U"});var z;if(z=x){var l=z=void 0;z=!c||!i.per_phrase||!c.count||c.count<i.per_phrase;l=!i.per_page||v<i.per_page;
z=z&&l&&s(n,c)}if(z&&(z=c,l=void 0,l=e.createEl("a"),l.innerHTML=x.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"\x3cspan\x3e$1\x3c/span\x3e"),l.className="vglnk",e.cache(l,"type","inserted"),e.cache(l,"phrase",x),i.ui&&(l.title="Link added by VigLink"),u.initLink(l,z),x=l,!e.cache(x,"unlinked"))){"U"===c.type?T++:"L"===c.type.toUpperCase()?X++:ca++;p.insertBefore(x,n);p.removeChild(n);var n=c,J=l=z=void 0,k=void 0,D={el:x,segments:[]};x=x.getElementsByTagName("span");var L={els:[]};z=0;for(l=x.length;z<
l;z++)J=x[z],void 0===k||J.offsetTop===k.offsetTop?L.els.push(J):(D.segments.push(L),L={els:[J]}),k=J;L.geometry=e.geometry.apply(e,L.els);D.segments.push(L);n.links=n.links||[];n.links.push(D);c.count++;v++}n=q}},W=e.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(c){return e.matches(c,"a[href]")}}),$=function(c){var s;if(c){if(W(c,
{ancestors:!1,self:!0}))for(s=c.firstChild;s;)c=s.nextSibling,1===s.nodeType?$(s):3===s.nodeType&&D(s),s=c}else e.each(e.select(i.scope),function(c){W(c,{ancestors:!0,self:!1})&&$(c)})};u={addPhrasesToMatcher:function(c){var i="";"regexp"===e.type(c)?i=c.source:"array"===e.type(c)&&(i="(?:^|[\\s\"'\\(])("+e.map(c,e.escapeRegExp).join("|")+")(?\x3d\\s|\\W*$|\\W{2})");""!==i&&(m=RegExp(m?"(?:"+i+"|"+m.source+")":i,"i"))},focusLink:function(c){c.id||(c.id=e.uniqid("vl-link-"));location.href.hash="#"+
c.id;window.scrollBy(0,-150)},getPhrases:function(){var c=r.getPostIDs();q.api("insert",e.extend(u.getPartnerParams(),{cat:i.cat,mode:i.mode,pt:i.platform,ps:i.product_source,i:c?c.join("|"):null,u:location.href,type:i.type}),{fn:e.bind(u.onInsertApi,u)})},getPartnerParams:function(){var c,e,i=q.opt("partner"),n={};for(c in i)break;if(c)for(e in i[c])n[c+"_"+e]=i[c][e];return n},initLink:function(c,s,m){if(m=i.link_target||m)c.target=m;c.rel="nofollow";c.href||(c.href=s.url);e.cache(c,"params",{exp:p,
key:i.key,mid:s.mid,type:s.type||null});e.cache(c,"href",c.href);q.link(c)},insertLinks:function(c){Y=e.extend(Y,c);Y.timing&&(Y.data&&m)&&($(),u.log())},loadPhrases:function(c){var e,i,n,m=[];e=0;for(i=c.length;e<i;e++)n=c[e],n.phrase&&n.url&&(n.phrase=n.phrase.toLowerCase(),y[n.phrase]||(m.push(n.phrase),y[n.phrase]={count:y[n.phrase]?y[n.phrase].count:0,phrase:n.phrase,mid:n.mid,url:n.url,type:n.type||""}));0<m.length&&this.addPhrasesToMatcher(m);this.insertLinks({data:!0})},log:function(){var e,
i,m={heavy:[],lite:[]},n=function(c,e){return e.split(",")[0]-c.split(",")[0]};for(e in y)i=parseInt(y[e].count,10),0<i&&(i=[i,e.replace(/\|/g,"%7C")].join(),m["L"===y[e].type.toUpperCase()?"lite":"heavy"].push(i));m.lite.sort(n);m.heavy.sort(n);c("insert",[{ct:v,cl:X,ch:ca,cu:T,exp:p},{pl:m.lite.join("|")},{ph:m.heavy.join("|")}])},onInsertApi:function(c){"object"===e.type(c)&&(p=c.exp,c.results&&this.loadPhrases(c.results))},setup:function(){i.scope=i.scope||r.scope||"body";i.link_urls&&this.addPhrasesToMatcher(RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()\x3c\x3e]+|\\((?:[^\\s()\x3c\x3e]|(?:\\([^\\s()\x3c\x3e]+\\)))*\\))+(?:\\((?:[^\\s()\x3c\x3e]|(?:\\([^\\s()\x3c\x3e]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,\x3c\x3e?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))",
"i"));if(i.link_phrases)if(!i.platform||"full"===i.platform)this.getPhrases();else e.on("DOMReady",e.bind(this.getPhrases,this))}};u.setup();return function(){e.on("DOMReady",function(){u.insertLinks({timing:!0})})}}};window.vglnk=window.vglnk||{};window.vglnk.spotlight_plugin=function(i,e,q){window.vglnk.spotlight_plugin.exports={$:e,opts:i,vglnk:q};return function(){(!e.browser.ie||6<e.browser.version)&&e.jsonp(q.opt("asset_url")+"/spotlight.js")}};